### ISSUE TITLE
Update zend-component-installer version to 0.7 in composer.json

### ISSUE THREAD

**Issue by seyfer** [zendframework/zend-skeleton-installer#8]
Please, update

"zendframework/zend-component-installer": "^1.0 || ^0.3 || ^1.0.0-dev@dev",

to

"zendframework/zend-component-installer": "^1.0 || ^0.7 || ^1.0.0-dev@dev",

in order to solve this issue

https://github.com/zendframework/zend-component-installer/issues/28

thanks!

**Comment by Xerkus** [comment]
Fixed in #7
